apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /setreplaceall
  name: setreplaceall
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|setreplaceall'
data:
  by-path: spec.forProvider.vpcIdRef.name
  by-value: mec-eks-vpc
  put-value: mec-new-eks-vpc
