apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata: # kpt-merge: /mec-new-eks-vpc-igw
  name: mec-new-eks-vpc-igw
  annotations:
    internal.kpt.dev/upstream-identifier: 'ec2.aws.crossplane.io|InternetGateway|default|mec-new-eks-vpc-igw'
spec:
  forProvider:
    region: us-west-2
    vpcIdRef:
      name: mec-new-eks-vpc
  providerConfigRef:
    name: default
