apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata: # kpt-merge: /mec-new-eks-vpc-rgt
  name: mec-new-eks-vpc-rgt
  annotations:
    internal.kpt.dev/upstream-identifier: 'ec2.aws.crossplane.io|RouteTable|default|mec-new-eks-vpc-rgt'
spec:
  forProvider:
    region: us-west-2
    routes:
    - destinationCidrBlock: 0.0.0.0/0
      gatewayIdRef:
        name: mec-new-eks-vpc-igw
    associations:
    - subnetIdRef:
        name: mec-new-eks-vpc-s1
    - subnetIdRef:
        name: mec-new-eks-vpc-s2
    vpcIdRef:
      name: mec-new-eks-vpc
  providerConfigRef:
    name: default
