apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata: # kpt-merge: /mec-new-eks-vpc-s1
  name: mec-new-eks-vpc-s1
  annotations:
    internal.kpt.dev/upstream-identifier: 'ec2.aws.crossplane.io|Subnet|default|mec-new-eks-vpc-s1'
spec:
  forProvider:
    region: us-west-2
    availabilityZone: us-west-2a
    cidrBlock: 10.0.1.0/24
    vpcIdRef:
      name: mec-new-eks-vpc
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata: # kpt-merge: /mec-new-eks-vpc-s2
  name: mec-new-eks-vpc-s2
  annotations:
    internal.kpt.dev/upstream-identifier: 'ec2.aws.crossplane.io|Subnet|default|mec-new-eks-vpc-s2'
spec:
  forProvider:
    region: us-west-2
    availabilityZone: us-west-2b
    cidrBlock: 10.0.4.0/24
    vpcIdRef:
      name: mec-new-eks-vpc
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata: # kpt-merge: /mec-new-eks-vpc-s3
  name: mec-new-eks-vpc-s3
  annotations:
    internal.kpt.dev/upstream-identifier: 'ec2.aws.crossplane.io|Subnet|default|mec-new-eks-vpc-s3'
spec:
  forProvider:
    region: us-west-2
    availabilityZone: us-west-2c
    cidrBlock: 10.0.2.0/24
    vpcIdRef:
      name: mec-new-eks-vpc
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata: # kpt-merge: /mec-new-eks-vpc-s4
  name: mec-new-eks-vpc-s4
  annotations:
    internal.kpt.dev/upstream-identifier: 'ec2.aws.crossplane.io|Subnet|default|mec-new-eks-vpc-s4'
spec:
  forProvider:
    region: us-west-2
    availabilityZone: us-west-2d
    cidrBlock: 10.0.3.0/24
    vpcIdRef:
      name: mec-new-eks-vpc
  providerConfigRef:
    name: default
