apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata: # kpt-merge: /mec-new-eks-vpc
  name: mec-new-eks-vpc
  annotations:
    internal.kpt.dev/upstream-identifier: 'ec2.aws.crossplane.io|VPC|default|mec-new-eks-vpc'
spec:
  forProvider:
    region: us-west-2
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
  providerConfigRef:
    name: default
